package com.acm.acmwebsite.feature.controller;

import com.acm.acmwebsite.feature.dto.commiteedtos.CommitteeDto;
import com.acm.acmwebsite.feature.dto.commiteedtos.SubscriptionDto;
import com.acm.acmwebsite.feature.entity.Committee;
import com.acm.acmwebsite.feature.entity.Message;
import com.acm.acmwebsite.feature.entity.Subscription;
import com.acm.acmwebsite.feature.enums.subscriptionStatus;
import com.acm.acmwebsite.feature.repository.MessageRepository;
import com.acm.acmwebsite.feature.service.CommitteService;
import com.acm.acmwebsite.feature.service.MessageService;
import com.acm.acmwebsite.feature.service.SubscriptionService;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;


import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/committee")
public class CommitteeController {
    private  CommitteService committeeService;
    private SubscriptionService subscriptionService;
    private MessageService messageService;

    @Autowired
    public void setCommitteeService(CommitteService committeeService,SubscriptionService subscriptionService,MessageService messageService) {
        this.committeeService = committeeService;
        this.subscriptionService = subscriptionService;
        this.messageService = messageService;
    }
    @GetMapping
    List<CommitteeDto> getCommittees(){
        return  committeeService.getAll()
                .stream().map(Committee -> {return new CommitteeDto(Committee.getId(),Committee.getName(),
                        Committee.getDescription(),
                        Committee.getLogoUrl(),
                        Committee.getCallMessage(),
                        Committee.isOpen(),
                        Committee.getTopicToken(),
                        Committee.getApplicationFormLink());}).toList();
    }
    // to avoid this Reddundancy in code I suggest using mappers and add its dependencies
    @GetMapping("/{id}")
    public ResponseEntity<CommitteeDto> getCommitteeById(@PathVariable Long id){
        var committee = committeeService.getById(id);
        if(committee == null){
            return ResponseEntity.notFound().build();
        }

        return ResponseEntity.ok( new CommitteeDto(committee.getId(),committee.getName(),
                committee.getDescription(),
                committee.getLogoUrl(),
                committee.getCallMessage(),
                committee.isOpen(),
                committee.getTopicToken(),
                committee.getApplicationFormLink()));
    }


    @PutMapping("/{id}")
    public ResponseEntity<?> updateCommittee(@PathVariable Long id,
    @RequestBody CommitteeDto committeeDto){
     var committee=committeeService.getById(id);
     if(committee==null){
            return ResponseEntity.notFound().build();
     }
     //ignored updating id as it is auto generated by the system
     if(committeeDto.getName()!=null)
       committee.setName(committeeDto.getName());
     if(committeeDto.getDescription()!=null)
       committee.setDescription(committeeDto.getDescription());
     if(committeeDto.getLogoUrl()!=null)
       committee.setLogoUrl(committeeDto.getLogoUrl());
      if(committeeDto.getApplicationFormLink()!=null)
       committee.setApplicationFormLink(committeeDto.getApplicationFormLink());

      try {
          committeeService.save(committee);
      }
      catch (Exception e){
          return ResponseEntity.badRequest().body(Map.of("message",e.getMessage()));
      }

     return ResponseEntity.ok(new CommitteeDto(committee.getId(),committee.getName(),committee.getDescription()
     ,committee.getLogoUrl(),committee.getCallMessage(),committee.isOpen(),committee.getTopicToken(),committee.getApplicationFormLink()));

    }

    @PostMapping
    public ResponseEntity<?>  createCommittee(@RequestBody CommitteeDto committeeDto){
        // I ignored id as it is auto generated by the system
        var newCommittee=new Committee(
                committeeDto.getName(),
                committeeDto.getDescription(),
                committeeDto.getLogoUrl(),
                committeeDto.isOpen(),
                committeeDto.getCallMessage(),
                committeeDto.getApplicationFormLink());
        try {
            committeeService.save(newCommittee);
        }
        catch (Exception e){
            return ResponseEntity.badRequest().body(Map.of("message","this committee is already exist"));
        }

        return ResponseEntity.ok(new CommitteeDto(newCommittee.getId(),
                newCommittee.getName(), newCommittee.getDescription(), newCommittee.getLogoUrl()
        ,newCommittee.getCallMessage(), newCommittee.isOpen(),newCommittee.getTopicToken() ,newCommittee.getApplicationFormLink()));

    }

    @DeleteMapping("/{id}")
    @Transactional
    public ResponseEntity<Void> deleteCommittee(@PathVariable Long id){
        var committee=committeeService.getById(id);
        if(committee==null){
            return ResponseEntity.notFound().build();
        }
        committeeService.delete(id);
        subscriptionService.deleteByTopic(committee.getTopicToken());
        return ResponseEntity.ok().build();
    }


    @PostMapping("/{id}/open-call")
    public ResponseEntity<?> openCall(@PathVariable Long id){
        var committee=committeeService.getById(id);
        if(committee==null){
            return ResponseEntity.notFound().build();
        }
        if(committee.isOpen())
        {
            return ResponseEntity.badRequest().body(Map.of("open","the call is already open!"));
        }

        committee.setOpen(true);
        committeeService.save(committee);
        committeeService.sendCallMessage(committee.getTopicToken(),committee.getCallMessage());
        return ResponseEntity.ok().build();
    }

    @PostMapping("/{id}/close-call")
    public ResponseEntity<?> closeCall(@PathVariable Long id){
        var committee=committeeService.getById(id);
        if(committee==null){
            return ResponseEntity.notFound().build();
        }
        committee.setOpen(false);
        committeeService.save(committee);
        return ResponseEntity.ok().build();
    }


    //may admin need to change message without open the calls
    @PostMapping("{id}/change-message")
    @Transactional
    public ResponseEntity<?> changeCallMessage(@PathVariable Long id, @RequestBody Message message){
        var committee=committeeService.getById(id);
        if(committee==null){
            return ResponseEntity.notFound().build();
        }
        messageService.SaveMessage(message);
        committee.setCallMessage(message);
        committeeService.save(committee);
        return ResponseEntity.ok().build();
    }



    @PostMapping("/{id}/subscribe")
    public ResponseEntity<?> subscribe(@PathVariable Long id,
                                       @RequestBody SubscriptionDto subscriptionDto){
        var committee=committeeService.getById(id);
        if(committee==null){
            return ResponseEntity.notFound().build();
        }

        var subscription=subscriptionService.findByEmailAndTopic(subscriptionDto.getEmail(),committee.getTopicToken());
        if(subscription!=null){
            return ResponseEntity.badRequest().body(Map.of("email","is already subscribed!"));
        }
        var newSubscription=new  Subscription(subscriptionDto.getEmail(),committee.getTopicToken());
        subscriptionService.addSubscription(newSubscription);
        subscriptionService.sendConfirmationEmail(newSubscription,new Message("hello","your subscription to our MailingList has been confirmed"));
        return ResponseEntity.ok().build();

    }






}
