package com.acm.acmwebsite.feature.controller;

import com.acm.acmwebsite.feature.dto.commiteedtos.CommitteeDto;
import com.acm.acmwebsite.feature.entity.Committee;
import com.acm.acmwebsite.feature.service.CommitteService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.util.UriComponentsBuilder;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/committee")
public class CommitteeController {
    private  CommitteService committeeService;

    @Autowired
    public void setCommitteeService(CommitteService committeeService) {
        this.committeeService = committeeService;
    }
    @GetMapping
    List<CommitteeDto> getCommittees(){
        return  committeeService.getAll()
                .stream().map(Committee -> {return new CommitteeDto(Committee.getId(),Committee.getName(),
                        Committee.getDescription(),
                        Committee.getLogoUrl(),
                        Committee.getCallMessage(),
                        Committee.isOpen(),
                        Committee.getApplicationFormLink());}).toList();
    }
    // to avoid this reddundancy in code i suggest using mappers and add its dependencies
    @GetMapping("/{id}")
    public ResponseEntity<CommitteeDto> getCommitteeById(@PathVariable Long id){
        var committee = committeeService.getById(id);
        if(committee == null){
            return ResponseEntity.notFound().build();
        }

        return ResponseEntity.ok( new CommitteeDto(committee.getId(),committee.getName(),
                committee.getDescription(),
                committee.getLogoUrl(),
                committee.getCallMessage(),
                committee.isOpen(),
                committee.getApplicationFormLink()));
    }


    @PutMapping("/{id}")
    public ResponseEntity<CommitteeDto> updateCommittee(@PathVariable Long id,
    @RequestBody CommitteeDto committeeDto){
     var committee=committeeService.getById(id);
     if(committee==null){
            return ResponseEntity.notFound().build();
     }
     //ignored updating id as it is auto generated by the system
     if(committeeDto.getName()!=null)
       committee.setName(committeeDto.getName());
     if(committeeDto.getDescription()!=null)
       committee.setDescription(committeeDto.getDescription());
     if(committeeDto.getLogoUrl()!=null)
       committee.setLogoUrl(committeeDto.getLogoUrl());
     if(committeeDto.getCallMessage()!=null)
       committee.setCallMessage(committeeDto.getCallMessage());
      if(committeeDto.getApplicationFormLink()!=null)
       committee.setApplicationFormLink(committeeDto.getApplicationFormLink());
      if(committeeDto.isOpen()^committee.isOpen())
       committee.setOpen(committeeDto.isOpen());



     committeeService.save(committee);
     return ResponseEntity.ok(new CommitteeDto(committee.getId(),committee.getName(),committee.getDescription()
     ,committee.getLogoUrl(),committee.getCallMessage(),committee.isOpen(),committee.getApplicationFormLink()));

    }

    @PostMapping
    public ResponseEntity<?>  createCommittee(@RequestBody CommitteeDto committeeDto){
        if(committeeService.existsByName(committeeDto.getName()))
            return ResponseEntity.badRequest().body(Map.of("name","Name is already exists!"));
        // i ignored id as it is auto generated by the system
        var newCommittee=new Committee(
                committeeDto.getName(),
                committeeDto.getDescription(),
                committeeDto.getLogoUrl(),
                committeeDto.isOpen(),
                committeeDto.getCallMessage(),
                committeeDto.getApplicationFormLink() );
        committeeService.save(newCommittee);
        return ResponseEntity.ok(new CommitteeDto(newCommittee.getId(),
                newCommittee.getName(), newCommittee.getDescription(), newCommittee.getLogoUrl()
        ,newCommittee.getCallMessage(), newCommittee.isOpen(), newCommittee.getApplicationFormLink()));

    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteCommittee(@PathVariable Long id){
        var committee=committeeService.getById(id);
        if(committee==null){
            return ResponseEntity.notFound().build();
        }
        committeeService.delete(id);
        return ResponseEntity.ok().build();
    }





}
