name: PR Coverage Comment

on:
  workflow_run:
    workflows: ["ACM Website CI/CD"]
    types:
      - completed

jobs:
  comment:
    name: Comment PR Coverage
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
    steps:
      - name: Download PR Coverage Data
        uses: actions/download-artifact@v4
        with:
          name: pr-coverage-data
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Read PR number
        id: pr_info
        run: echo "PR_NUMBER=$(cat pr_number)" >> $GITHUB_OUTPUT

      - name: Comment Coverage on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.pr_info.outputs.PR_NUMBER }}
          path: coverage_body.md
          recreate: true
